In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('titanic')

In [4]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [7]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [9]:
df.drop(['class', 'who', 'adult_male', 'deck', 'embark_town', 'alive'], axis=1, inplace=True)

In [10]:
df

     survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0           0       3    male  22.0      1      0   7.2500        S  False
1           1       1  female  38.0      1      0  71.2833        C  False
2           1       3  female  26.0      0      0   7.9250        S   True
3           1       1  female  35.0      1      0  53.1000        S  False
4           0       3    male  35.0      0      0   8.0500        S   True
..        ...     ...     ...   ...    ...    ...      ...      ...    ...
886         0       2    male  27.0      0      0  13.0000        S   True
887         1       1  female  19.0      0      0  30.0000        S   True
888         0       3  female   NaN      1      2  23.4500        S  False
889         1       1    male  26.0      0      0  30.0000        C   True
890         0       3    male  32.0      0      0   7.7500        Q   True

[891 rows x 9 columns]

In [11]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [12]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.000000,1,0,7.2500,S,False
1,1,1,female,38.000000,1,0,71.2833,C,False
2,1,3,female,26.000000,0,0,7.9250,S,True
3,1,1,female,35.000000,1,0,53.1000,S,False
4,0,3,male,35.000000,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,True
887,1,1,female,19.000000,0,0,30.0000,S,True
888,0,3,female,29.699118,1,2,23.4500,S,False
889,1,1,male,26.000000,0,0,30.0000,C,True
890,0,3,male,32.000000,0,0,7.7500,Q,True

In [13]:
df.dropna(subset=['embarked'], inplace=True)

In [14]:
df.isna().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
alone       0
dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [16]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.000000,1,0,7.2500,S,False
1,1,1,female,38.000000,1,0,71.2833,C,False
2,1,3,female,26.000000,0,0,7.9250,S,True
3,1,1,female,35.000000,1,0,53.1000,S,False
4,0,3,male,35.000000,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,True
887,1,1,female,19.000000,0,0,30.0000,S,True
888,0,3,female,29.699118,1,2,23.4500,S,False
889,1,1,male,26.000000,0,0,30.0000,C,True
890,0,3,male,32.000000,0,0,7.7500,Q,True

In [17]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [18]:
df['sex'] = lb.fit_transform(df['sex'])

In [19]:
df['embarked'].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [20]:
df['embarked'] = lb.fit_transform(df['embarked'])

In [21]:
df

     survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  22.000000      1      0   7.2500         2  False
1           1       1    0  38.000000      1      0  71.2833         0  False
2           1       3    0  26.000000      0      0   7.9250         2   True
3           1       1    0  35.000000      1      0  53.1000         2  False
4           0       3    1  35.000000      0      0   8.0500         2   True
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  27.000000      0      0  13.0000         2   True
887         1       1    0  19.000000      0      0  30.0000         2   True
888         0       3    0  29.699118      1      2  23.4500         2  False
889         1       1    1  26.000000      0      0  30.0000         0   True
890         0       3    1  32.000000      0      0   7.7500         1   True

[889 rows x 9 columns]

In [22]:
df = df.astype(int)

In [23]:
x = df.drop('survived', axis=1)
y = df['survived']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [28]:
y_pred = model.predict(x_test)

In [29]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [31]:
accuracy_score(y_test, y_pred)

0.8033707865168539

In [32]:
confusion_matrix(y_test, y_pred)

array([[90, 19],
       [16, 53]])

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178

In [34]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
scalar = StandardScaler()
knn_df = scalar.fit_transform(df)

In [37]:
knn_df

array([[-0.78696114,  0.82520863,  0.73534203, ..., -0.49673282,
         0.58683958, -1.22934919],
       [ 1.27071078, -1.57221121, -1.35991138, ...,  0.79153916,
        -1.93955453, -1.22934919],
       [ 1.27071078,  0.82520863, -1.35991138, ..., -0.49673282,
         0.58683958,  0.81343853],
       ...,
       [-0.78696114,  0.82520863, -1.35991138, ..., -0.17466483,
         0.58683958, -1.22934919],
       [ 1.27071078, -1.57221121,  0.73534203, ..., -0.03376008,
        -1.93955453,  0.81343853],
       [-0.78696114,  0.82520863,  0.73534203, ..., -0.49673282,
        -0.67635748,  0.81343853]], shape=(889, 9))

In [38]:
x_train_scaled = scalar.fit_transform(x_train)
x_test_scaled = scalar.fit_transform(x_test)

In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [40]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [41]:
y_pred_knn = model.predict(x_test_scaled)

In [42]:
y_pred_knn

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [43]:
accuracy_score(y_test, y_pred_knn)

0.7808988764044944

In [44]:
confusion_matrix(y_test, y_pred_knn)

array([[90, 19],
       [20, 49]])

In [45]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82       109
           1       0.72      0.71      0.72        69

    accuracy                           0.78       178
   macro avg       0.77      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178

In [46]:
x_train

     pclass  sex  age  sibsp  parch  fare  embarked  alone
708       1    0   22      0      0   151         2      1
240       3    0   29      1      0    14         0      0
382       3    1   32      0      0     7         2      1
792       3    0   29      8      2    69         2      0
683       3    1   14      5      2    46         2      0
..      ...  ...  ...    ...    ...   ...       ...    ...
107       3    1   29      0      0     7         2      1
271       3    1   25      0      0     0         2      1
862       1    0   48      0      0    25         2      1
436       3    0   21      2      2    34         2      0
103       3    1   33      0      0     8         2      1

[711 rows x 8 columns]

In [47]:
y_train

708    1
240    0
382    0
792    0
683    0
      ..
107    1
271    1
862    1
436    0
103    0
Name: survived, Length: 711, dtype: int64

In [48]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()
model_NB.fit(x_train, y_train)

GaussianNB()

In [50]:
y_pred_nb = model_NB.predict(x_test)

In [51]:
y_pred_nb

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [52]:
accuracy_score(y_test, y_pred_nb)

0.7752808988764045

In [53]:
confusion_matrix(y_test, y_pred_nb)

array([[84, 25],
       [15, 54]])

In [54]:
print(classification_report(y_test, y_pred_nb))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:
model_DT = DecisionTreeClassifier(random_state=42)

In [67]:
model_DT.fit(x_train_scaled, y_train)

DecisionTreeClassifier(random_state=42)

In [68]:
y_pred_DT = model_DT.predict(x_test_scaled)

In [69]:
accuracy_score(y_test, y_pred_DT)

0.7696629213483146

In [70]:
confusion_matrix(y_test, y_pred_DT)

array([[88, 21],
       [20, 49]])

In [71]:
print(classification_report(y_test, y_pred_DT))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       109
           1       0.70      0.71      0.71        69

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178

In [72]:
from sklearn.svm import SVC
model_svm = SVC(kernel='rbf')

In [74]:
model_svm.fit(x_train_scaled, y_train)

SVC()

In [75]:
y_pred_svm = model_svm.predict(x_test_scaled)

In [76]:
accuracy_score(y_test, y_pred_svm)

0.8258426966292135

In [77]:
confusion_matrix(y_test, y_pred_svm)

array([[96, 13],
       [18, 51]])

In [78]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178